#!/usr/bin/env python3
"""Generate dashboard/data.js — embeds tracking and jobs data for offline viewing.

Called automatically whenever tracking state changes (via local_server.py) and
on dashboard launch. The HTML pages load this file via <script src="data.js">
and fall back to the embedded data when no API is reachable.
"""

import json
import os
import re
from pathlib import Path

PROJECT_DIR = Path(os.environ.get("JOB_SEARCH_DIR", Path(__file__).parent.parent))
TRACKING_FILE = PROJECT_DIR / "data" / "tracking.json"
ALL_JOBS_FILE = PROJECT_DIR / "data" / "jobs" / "all-jobs.json"
MATCHES_FILE = PROJECT_DIR / "data" / "connection-matches.json"
OUTPUTS_DIR = PROJECT_DIR / "outputs"
OUTPUT_FILE = PROJECT_DIR / "dashboard" / "data.js"

SKIP_DIRS = {"daily-summaries", "cover-letters", "connection-requests"}


def scan_tailored_messages(all_jobs):
    """Scan outputs/[company]/[role]/connection-request-recruiter.md files.

    Returns a dict keyed by "company|||title" matching jobKey() in jobs.html.
    """
    messages = {}
    if not OUTPUTS_DIR.exists():
        return messages

    for company_dir in OUTPUTS_DIR.iterdir():
        if not company_dir.is_dir() or company_dir.name in SKIP_DIRS:
            continue
        for role_dir in company_dir.iterdir():
            if not role_dir.is_dir():
                continue
            cr_file = role_dir / "connection-request-recruiter.md"
            if not cr_file.exists():
                continue
            msg = cr_file.read_text().strip()
            if not msg:
                continue

            company_slug = company_dir.name
            role_slug = role_dir.name

            for j in all_jobs:
                j_company = j.get("company") or ""
                j_title = j.get("title") or ""
                j_company_slug = re.sub(r"[^a-z0-9]+", "-", j_company.lower()).strip("-")
                j_title_slug = re.sub(r"[^a-z0-9]+", "-", j_title.lower()).strip("-")

                if (j_company_slug == company_slug or
                    j_company_slug.startswith(company_slug) or
                    company_slug.startswith(j_company_slug)):
                    if (j_title_slug.startswith(role_slug) or
                        role_slug.startswith(j_title_slug[:len(role_slug)])):
                        key = f"{j_company}|||{j_title}"
                        if key not in messages:
                            messages[key] = msg
                        break

    return messages


def _load_json(path, default):
    if not path.exists():
        return default
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return default


def generate():
    tracking = _load_json(TRACKING_FILE, {
        "metadata": {"version": "3.0", "created": "", "last_updated": ""},
        "applications": [],
        "unlinked_outreach": [],
        "legacy_applications": [],
        "stats": {},
    })
    all_jobs = _load_json(ALL_JOBS_FILE, [])
    matches = _load_json(MATCHES_FILE, {})
    tailored = scan_tailored_messages(all_jobs)

    js = (
        "// Auto-generated by generate_data_js.py — do not edit\n"
        f"window.TRACKING_DATA = {json.dumps(tracking)};\n"
        f"window.ALL_JOBS_DATA = {json.dumps(all_jobs)};\n"
        f"window.CONNECTION_MATCHES = {json.dumps(matches.get('matches', {}))};\n"
        f"window.TAILORED_MESSAGES = {json.dumps(tailored)};\n"
    )

    os.makedirs(OUTPUT_FILE.parent, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(js)

    return len(all_jobs), len(tracking.get("applications", []))


if __name__ == "__main__":
    jobs_count, apps_count = generate()
    print(f"Generated {OUTPUT_FILE} ({jobs_count} jobs, {apps_count} applications)")
