#!/usr/bin/env python3
"""Generate dashboard/data.js — embeds tracking and jobs data for offline viewing.

Called automatically whenever tracking state changes (via local_server.py) and
on dashboard launch. The HTML pages load this file via <script src="data.js">
and fall back to the embedded data when no API is reachable.
"""

import json
import os
import re
from pathlib import Path

PROJECT_DIR = Path(os.environ.get("JOB_SEARCH_DIR", Path(__file__).parent.parent))
TRACKING_FILE = PROJECT_DIR / "data" / "tracking.json"
ALL_JOBS_FILE = PROJECT_DIR / "data" / "jobs" / "all-jobs.json"
MATCHES_FILE = PROJECT_DIR / "data" / "connection-matches.json"
OUTPUTS_DIR = PROJECT_DIR / "outputs"
OUTPUT_FILE = PROJECT_DIR / "dashboard" / "data.js"

SKIP_DIRS = {"daily-summaries", "cover-letters", "connection-requests"}


def scan_tailored_messages(all_jobs):
    """Scan outputs/[company]/[role]/connection-request-recruiter.md files.

    Returns a dict keyed by "company|||title" matching jobKey() in jobs.html.
    """
    messages = {}
    if not OUTPUTS_DIR.exists():
        return messages

    for company_dir in OUTPUTS_DIR.iterdir():
        if not company_dir.is_dir() or company_dir.name in SKIP_DIRS:
            continue
        for role_dir in company_dir.iterdir():
            if not role_dir.is_dir():
                continue
            cr_file = role_dir / "connection-request-recruiter.md"
            if not cr_file.exists():
                continue
            msg = cr_file.read_text().strip()
            if not msg:
                continue

            company_slug = company_dir.name
            role_slug = role_dir.name

            for j in all_jobs:
                j_company = j.get("company") or ""
                j_title = j.get("title") or ""
                j_company_slug = re.sub(r"[^a-z0-9]+", "-", j_company.lower()).strip("-")
                j_title_slug = re.sub(r"[^a-z0-9]+", "-", j_title.lower()).strip("-")

                if (j_company_slug == company_slug or
                    j_company_slug.startswith(company_slug) or
                    company_slug.startswith(j_company_slug)):
                    if (j_title_slug.startswith(role_slug) or
                        role_slug.startswith(j_title_slug[:len(role_slug)])):
                        key = f"{j_company}|||{j_title}"
                        if key not in messages:
                            messages[key] = msg
                        break

    return messages


def _load_json(path, default):
    if not path.exists():
        return default
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return default


def _aggregate_companies(matches_data):
    """Build a tiered company list from connection-matches.json.

    Groups matches by company, deduplicates connections, assigns tiers:
      tier1: 3+ connections
      tier2: 2 connections
      tier3: 1 connection
    """
    raw_matches = matches_data.get("matches", {})
    if not raw_matches:
        return {"tier1": [], "tier2": [], "tier3": []}

    # Group connections by company (dedup by name)
    by_company = {}
    for key, conns in raw_matches.items():
        parts = key.split("|||")
        company = parts[0] if parts else ""
        if not company:
            continue
        if company not in by_company:
            by_company[company] = {}
        for c in conns:
            name = c.get("name", "")
            if name and name not in by_company[company]:
                by_company[company][name] = {
                    "name": name,
                    "position": c.get("position", ""),
                }

    # Build tiered list
    companies = []
    for company, conns_dict in by_company.items():
        conn_list = list(conns_dict.values())
        count = len(conn_list)
        if count >= 3:
            tier = 1
        elif count == 2:
            tier = 2
        else:
            tier = 3
        companies.append({
            "company": company,
            "score": count * 10,
            "tier": tier,
            "connection_count": count,
            "connections": conn_list,
        })

    companies.sort(key=lambda x: (-x["score"], x["company"]))

    result = {"tier1": [], "tier2": [], "tier3": []}
    for c in companies:
        result[f"tier{c['tier']}"].append(c)

    return result


def generate():
    tracking = _load_json(TRACKING_FILE, {
        "metadata": {"version": "3.0", "created": "", "last_updated": ""},
        "applications": [],
        "unlinked_outreach": [],
        "legacy_applications": [],
        "stats": {},
    })
    all_jobs = _load_json(ALL_JOBS_FILE, [])
    matches = _load_json(MATCHES_FILE, {})
    tailored = scan_tailored_messages(all_jobs)
    companies = _aggregate_companies(matches)

    js = (
        "// Auto-generated by generate_data_js.py — do not edit\n"
        f"window.TRACKING_DATA = {json.dumps(tracking)};\n"
        f"window.ALL_JOBS_DATA = {json.dumps(all_jobs)};\n"
        f"window.CONNECTION_MATCHES = {json.dumps(matches.get('matches', {}))};\n"
        f"window.TAILORED_MESSAGES = {json.dumps(tailored)};\n"
        f"window.COMPANIES_DATA = {json.dumps(companies)};\n"
    )

    os.makedirs(OUTPUT_FILE.parent, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(js)

    return len(all_jobs), len(tracking.get("applications", []))


if __name__ == "__main__":
    jobs_count, apps_count = generate()
    print(f"Generated {OUTPUT_FILE} ({jobs_count} jobs, {apps_count} applications)")
